#  workflow
name: github action 실행시키기

# Event: 어떤 시점에 실행시킬지 정의
on:
  push:
    branches:
      - main

# Job: 실행시킬 작업 정의
# 여러 Job은 기본적으로 병렬로 실행된다.
jobs:
  # Job 이름 정의
  my-deploy-job:
    # 실행 환경 정의
    runs-on: ubuntu-latest

    # 실행할 작업 단위
    # Job은 여러 step들로 구성될 수 있어
    steps:
      # 작업 이름 정의
      - name: Hello world 찍기
        run: echo "Hello world"
      - name: 여러 명렁어 작성
        run: |
          echo "Hello world"
          echo "Hello world2"
          echo "Hello world3"

      - name: 파일 생성
        run: echo "Hello world" > hello.txt

      - name: Github actions 변수 사용하기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_TOKEN
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REPOSITORY_OWNER
          echo $GITHUB_REPOSITORY_OWNER_NAME
          echo $GITHUB_REPOSITORY_OWNER_EMAIL
          echo $GITHUB_REPOSITORY_OWNER_AVATAR_URL
          echo $GITHUB_REPOSITORY_OWNER_HTML_URL
